// Generated by scripts/widget-art/still.ts.
import src from "./cover-garage.webp";

export default {
  src,
  aspect: 489 / 420,
  quad: {
    tl: [0.0969, 0.1252],
    tr: [0.7166, 0.0851],
    br: [0.7153, 0.9858],
    bl: [0.0981, 0.935],
  },
} as const;
