// Generated by scripts/widget-art/still.ts.
import src from "./cover-window.webp";

export default {
  src,
  aspect: 369 / 420,
  quad: {
    tl: [0.0742, 0.094],
    tr: [0.6863, 0.0752],
    br: [0.6856, 0.9245],
    bl: [0.0749, 0.9038],
  },
} as const;
