// Generated by scripts/widget-art/still.ts.
import src from "./cover-curtain.webp";

export default {
  src,
  aspect: 401 / 420,
  quad: {
    tl: [0.0529, 0.0781],
    tr: [0.8265, 0.0459],
    br: [0.8256, 0.986],
    bl: [0.054, 0.9522],
  },
} as const;
