// Generated by scripts/widget-art/still.ts.
import src from "./cover-shutter.webp";

export default {
  src,
  aspect: 351 / 420,
  quad: {
    tl: [0.0906, 0.1545],
    tr: [0.6605, 0.1375],
    br: [0.6599, 0.9335],
    bl: [0.0913, 0.9134],
  },
} as const;
