import {
  Button,
  ResponsiveDialog,
  ResponsiveDialogBody,
  ResponsiveDialogContent,
  ResponsiveDialogDescription,
  ResponsiveDialogFooter,
  ResponsiveDialogHeader,
  ResponsiveDialogTitle,
  SchemaForm,
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@glasshome/widget-sdk";

export const widgetDialogProps = {
  ResponsiveDialog,
  ResponsiveDialogContent,
  ResponsiveDialogHeader,
  ResponsiveDialogTitle,
  ResponsiveDialogDescription,
  ResponsiveDialogBody,
  ResponsiveDialogFooter,
  Button,
  SchemaForm,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
} as const;
